// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef hi_h
#define hi_h
#include <FL/Fl.H>
void translate_cb(Fl_Widget *, void *);
void execute_cb(Fl_Widget *, void *);
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
extern Fl_Input *command;
extern Fl_Input *translation;
#include <FL/Fl_Button.H>
extern Fl_Button *translate_button;
extern Fl_Button *execute_button;
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *display;
#endif
