#!/usr/pkg/bin/bash
FELHUNVBPFX_1(){ FELHUNVBPFX_1_WORD='fel';FELHUNVBPFX_1_STEM='fel';FELHUNVBPFX_1_GCAT='Vbpfx';FELHUNVBPFX_1_MORPHEMES[0]='fel[stem]';FELHUNVBPFX_1_MORPHEMES[1]='Vbpfx';true; };FELHUNVBPFX_1;Num_1(){ Num_1_WORD='száztizenhármat';Num_1_STEM='három';Num_1_GCAT='Num';Num_1_MORPHEMES[0]='swConsonant';Num_1_MORPHEMES[1]='Npref1nn';Num_1_MORPHEMES[2]='swConsonant';Num_1_MORPHEMES[3]='Npref1n';Num_1_MORPHEMES[4]='három[stem]';Num_1_MORPHEMES[5]='Num';Num_1_MORPHEMES[6]='Acc';number='';
prevNpref='';
isOrdinal=false;
for(i=0;i<Num_1_MORPHEMES.length;++i){
  if(Num_1_MORPHEMES[i]==='Npref1nnn'){
    if((prevNpref.length===0||prevNpref.match(/^Npref[1-9]$/)===null)&&prevNpref.match(/^Npref[1-9]n$/)===null) number+='1';
    else if(prevNpref.match(/^Npref[1-9]n$/)!==null) number+='0';
  }
  else if(Num_1_MORPHEMES[i]==='Npref1nn'){
    if(prevNpref.length===0||prevNpref.match(/^Npref[1-9]$/)===null) number+='1';
  }
  else if(Num_1_MORPHEMES[i]==='Npref1n'){
    if(prevNpref==='Npref1nnn')number+='01';
    else number+='1';
  }
  else if(Num_1_MORPHEMES[i]==='Npref2n'){
    if(prevNpref==='Npref1nnn')number+='02';
    else number+='2';
  }
  else if(Num_1_MORPHEMES[i]==='Npref3n'){
    if(prevNpref==='Npref1nnn')number+='03';
    else number+='3';
  }
  else if(Num_1_MORPHEMES[i]==='Npref4n'){
    if(prevNpref==='Npref1nnn')number+='04';
    else number+='4';
  }
  else if(Num_1_MORPHEMES[i]==='Npref5n'){
    if(prevNpref==='Npref1nnn')number+='05';
    else number+='5';
  }
  else if(Num_1_MORPHEMES[i]==='Npref6n'){
    if(prevNpref==='Npref1nnn')number+='06';
    else number+='6';
  }
  else if(Num_1_MORPHEMES[i]==='Npref7n'){
    if(prevNpref==='Npref1nnn')number+='07';
    else number+='7';
  }
  else if(Num_1_MORPHEMES[i]==='Npref8n'){
    if(prevNpref==='Npref1nnn')number+='08';
    else number+='8';
  }
  else if(Num_1_MORPHEMES[i]==='Npref9n'){
    if(prevNpref==='Npref1nnn')number+='09';
    else number+='9';
  }
  else if(Num_1_MORPHEMES[i]==='Npref1'){
    if(prevNpref==='Npref1nn')number+='01';
    else number+='1';
  }
  else if(Num_1_MORPHEMES[i]==='Npref2'){
    if(prevNpref==='Npref1nn')number+='02';
    else number+='2';
  }
  else if(Num_1_MORPHEMES[i]==='Npref3'){
    if(prevNpref==='Npref1nn')number+='03';
    else number+='3';
  }
  else if(Num_1_MORPHEMES[i]==='Npref4'){
    if(prevNpref==='Npref1nn')number+='04';
    else number+='4';
  }
  else if(Num_1_MORPHEMES[i]==='Npref5'){
    if(prevNpref==='Npref1nn')number+='05';
    else number+='5';
  }
  else if(Num_1_MORPHEMES[i]==='Npref6'){
    if(prevNpref==='Npref1nn')number+='06';
    else number+='6';
  }
  else if(Num_1_MORPHEMES[i]==='Npref7'){
    if(prevNpref==='Npref1nn')number+='07';
    else number+='7';
  }
  else if(Num_1_MORPHEMES[i]==='Npref8'){
    if(prevNpref==='Npref1nn')number+='08';
    else number+='8';
  }
  else if(Num_1_MORPHEMES[i]==='Npref9'){
    if(prevNpref==='Npref1nn')number+='09';
    else number+='9';
  }
  else if(Num_1_MORPHEMES[i]==='egy[stem]'){
    if(prevNpref==='Npref1nnn')number+='001';
    else if(prevNpref==='Npref1nn')number+='01';
    else number+='1';
  }
  else if(Num_1_MORPHEMES[i]==='kettő[stem]'){
    if(prevNpref==='Npref1nnn')number+='002';
    else if(prevNpref==='Npref1nn')number+='02';
    else number+='2';
  }
  else if(Num_1_MORPHEMES[i]==='három[stem]'){
    if(prevNpref==='Npref1nnn')number+='003';
    else if(prevNpref==='Npref1nn')number+='03';
    else number+='3';
  }
  else if(Num_1_MORPHEMES[i]==='négy[stem]'){
    if(prevNpref==='Npref1nnn')number+='004';
    else if(prevNpref==='Npref1nn')number+='04';
    else number+='4';
  }
  else if(Num_1_MORPHEMES[i]==='öt[stem]'){
    if(prevNpref==='Npref1nnn')number+='005';
    else if(prevNpref==='Npref1nn')number+='05';
    else number+='5';
  }
  else if(Num_1_MORPHEMES[i]==='hat[stem]'){
    if(prevNpref==='Npref1nnn')number+='006';
    else if(prevNpref==='Npref1nn')number+='06';
    else number+='6';
  }
  else if(Num_1_MORPHEMES[i]==='hét[stem]'){
    if(prevNpref==='Npref1nnn')number+='007';
    else if(prevNpref==='Npref1nn')number+='07';
    else number+='7';
  }
  else if(Num_1_MORPHEMES[i]==='nyolc[stem]'){
    if(prevNpref==='Npref1nnn')number+='008';
    else if(prevNpref==='Npref1nn')number+='08';
    else number+='8';
  }
  else if(Num_1_MORPHEMES[i]==='kilenc[stem]'){
    if(prevNpref==='Npref1nnn')number+='009';
    else if(prevNpref==='Npref1nn')number+='09';
    else number+='9';
  }
  else if(Num_1_MORPHEMES[i]==='tíz[stem]'){
    if(prevNpref==='Npref1nnn')number+='010';
    else number+='10';
  }
  else if(Num_1_MORPHEMES[i]==='húsz[stem]'){
    if(prevNpref==='Npref1nnn')number+='020';
    else number+='20';
  }
  else if(Num_1_MORPHEMES[i]==='harminc[stem]'){
    if(prevNpref==='Npref1nnn')number+='030';
    else number+='30';
  }
  else if(Num_1_MORPHEMES[i]==='negyven[stem]'){
    if(prevNpref==='Npref1nnn')number+='040';
    else number+='40';
  }
  else if(Num_1_MORPHEMES[i]==='ötven[stem]'){
    if(prevNpref==='Npref1nnn')number+='050';
    else number+='50';
  }
  else if(Num_1_MORPHEMES[i]==='hatvan[stem]'){
    if(prevNpref==='Npref1nnn')number+='060';
    else number+='60';
  }
  else if(Num_1_MORPHEMES[i]==='hetven[stem]'){
    if(prevNpref==='Npref1nnn')number+='070';
    else number+='70';
  }
  else if(Num_1_MORPHEMES[i]==='nyolcvan[stem]'){
    if(prevNpref==='Npref1nnn')number+='080';
    else number+='80';
  }
  else if(Num_1_MORPHEMES[i]==='kilencven[stem]'){
    if(prevNpref==='Npref1nnn')number+='090';
    else number+='90';
  }
  else if(Num_1_MORPHEMES[i]==='száz[stem]'){
    if(prevNpref.length===0||prevNpref==='Npref1nnn')number+='100';
    else number+='00';
  }
  else if(Num_1_MORPHEMES[i]==='ezer[stem]'){
    if(prevNpref.length===0)number+='1000';
    else if(prevNpref==='Npref1nn') number+='00000';
    else if(prevNpref.match(/^Npref[1-9]n$/)!==null) number+='0000';
    else number+='000';
  }
  else;
  if(Num_1_MORPHEMES[i].startsWith('Npref')===true) prevNpref=Num_1_MORPHEMES[i];
  if(Num_1_MORPHEMES[i]==='Ik') isOrdinal=true;
}
if(isOrdinal===true) number+='.';
return number };Num_1;HIVHUNV_1(){ HIVHUNV_1_WORD='hívd';HIVHUNV_1_STEM='hív';HIVHUNV_1_GCAT='Verb';HIVHUNV_1_MORPHEMES[0]='hív[stem]';HIVHUNV_1_MORPHEMES[1]='Verb';HIVHUNV_1_MORPHEMES[2]='ConjDefSg2';if(typeof HIVHUNV_1_CON_2_IN!=='undefined') Android.Call(HIVHUNV_1_CON_2_IN);
else if(typeof Num_1_OUT!=='undefined'){

} };HIVHUNV_1 FELHUNVBPFX_1_OUT Num_1_OUT;