PRAGMA foreign_keys = ON;
BEGIN;

insert into ROOT_TYPE values('H');
insert into ROOT_TYPE values('N');

insert into LANGUAGES values('ENG', 'English', '1', 'english.fst');

insert into SYMBOLS values('Stem', 'ENG', 'Stem');
insert into SYMBOLS values('A', 'ENG', 'Adjective');
insert into SYMBOLS values('COMP', 'ENG', 'Comparative');
insert into SYMBOLS values('SUPER', 'ENG', 'Superlative');
insert into SYMBOLS values('Adv', 'ENG', 'Adverb');
insert into SYMBOLS values('Cmpl', 'ENG', 'Complementizer');
insert into SYMBOLS values('Conj', 'ENG', 'Conjunction');
insert into SYMBOLS values('Det', 'ENG', 'Determiner');
insert into SYMBOLS values('Def', 'ENG', 'Definite Article');
insert into SYMBOLS values('Indef', 'ENG', 'Indefinite Article');
insert into SYMBOLS values('fwConsonant', 'ENG', 'followed by consonant');
insert into SYMBOLS values('fwVowel', 'ENG', 'followed by vowel');
insert into SYMBOLS values('Inject', 'ENG', 'Interjection');
insert into SYMBOLS values('N', 'ENG', 'Noun');
insert into SYMBOLS values('1sg', 'ENG', '1st person singular');
insert into SYMBOLS values('2sg', 'ENG', '2nd person singular');
insert into SYMBOLS values('3sg', 'ENG', '3rd person singular');
insert into SYMBOLS values('1pl', 'ENG', '1st person plural');
insert into SYMBOLS values('2pl', 'ENG', '2nd person plural');
insert into SYMBOLS values('3pl', 'ENG', '3rd person plural');
insert into SYMBOLS values('2nd', 'ENG', '2nd person');
insert into SYMBOLS values('3rd', 'ENG', '3rd person');
insert into SYMBOLS values('CON', 'ENG', 'Constant');
insert into SYMBOLS values('GEN', 'ENG', 'Genitive');
insert into SYMBOLS values('NVC', 'ENG', 'Noun Verb Contraction');
insert into SYMBOLS values('PRES', 'ENG', 'Present');
insert into SYMBOLS values('PAST', 'ENG', 'Past');
insert into SYMBOLS values('wh', 'ENG', 'Wh question');
insert into SYMBOLS values('neut', 'ENG', 'Neutral');
insert into SYMBOLS values('masc', 'ENG', 'Masculine');
insert into SYMBOLS values('fem', 'ENG', 'Feminine');
insert into SYMBOLS values('Part', 'ENG', 'Particle');
insert into SYMBOLS values('Prep', 'ENG', 'Preposition');
insert into SYMBOLS values('Pron', 'ENG', 'Pronoun');
insert into SYMBOLS values('nom', 'ENG', 'Nominative');
insert into SYMBOLS values('acc', 'ENG', 'Accusative');
insert into SYMBOLS values('nomacc', 'ENG', 'NomAcc');
insert into SYMBOLS values('refmasc', 'ENG', 'Masculine');
insert into SYMBOLS values('reffem', 'ENG', 'Feminine');
insert into SYMBOLS values('refl', 'ENG', 'Reflexive');
insert into SYMBOLS values('NEG', 'ENG', 'Negation');
insert into SYMBOLS values('ref1sg', 'ENG', '1st person singular');
insert into SYMBOLS values('ref2sg', 'ENG', '2nd person singular');
insert into SYMBOLS values('ref3sg', 'ENG', '3rd person singular');
insert into SYMBOLS values('ref1pl', 'ENG', '1st person plural');
insert into SYMBOLS values('ref2pl', 'ENG', '2nd person plural');
insert into SYMBOLS values('ref3pl', 'ENG', '3rd person plural');
insert into SYMBOLS values('ref2nd', 'ENG', '2nd person');
insert into SYMBOLS values('Punct', 'ENG', 'Punctuation');
insert into SYMBOLS values('Apostrophe', 'ENG', 'Apostrophe');
insert into SYMBOLS values('DoubleApostrophe', 'ENG', 'DoubleApostrophe');
insert into SYMBOLS values('OpeningBracket', 'ENG', 'OpeningBracket');
insert into SYMBOLS values('ClosingBracket', 'ENG', 'ClosingBracket');
insert into SYMBOLS values('Comma', 'ENG', 'Comma');
insert into SYMBOLS values('Hyphen', 'ENG', 'Hyphen');
insert into SYMBOLS values('Dash', 'ENG', 'Dash');
insert into SYMBOLS values('FullStop', 'ENG', 'FullStop');
insert into SYMBOLS values('QuestionMark', 'ENG', 'QuestionMark');
insert into SYMBOLS values('BackTick', 'ENG', 'BackTick');
insert into SYMBOLS values('DoubleBackTick', 'ENG', 'DoubleBackTick');
insert into SYMBOLS values('Colon', 'ENG', 'Colon');
insert into SYMBOLS values('ExclamationMark', 'ENG', 'ExclamationMark');
insert into SYMBOLS values('SemiColon', 'ENG', 'SemiColon');
insert into SYMBOLS values('Quotes', 'ENG', 'Quotes');
insert into SYMBOLS values('OpeningSqBracket', 'ENG', 'OpeningSqBracket');
insert into SYMBOLS values('ClosingSqBracket', 'ENG', 'ClosingSqBracket');
insert into SYMBOLS values('V', 'ENG', 'Verb');
insert into SYMBOLS values('CONTR', 'ENG', 'Contraction');
insert into SYMBOLS values('PROG', 'ENG', 'Progressive');
insert into SYMBOLS values('PPART', 'ENG', 'Past Participle');
insert into SYMBOLS values('STR', 'ENG', 'Strong');
insert into SYMBOLS values('Aux', 'ENG', 'Auxiliary');
insert into SYMBOLS values('Modal', 'ENG', 'Modal');
insert into SYMBOLS values('VVC', 'ENG', 'Verb Verb Contraction');
insert into SYMBOLS values('Num','ENG','Numeral');
insert into SYMBOLS values('ord','ENG','ordinal');
insert into SYMBOLS values('Npref1n','ENG','Decadal prefix');
insert into SYMBOLS values('Npref2n','ENG','Decadal prefix');
insert into SYMBOLS values('Npref3n','ENG','Decadal prefix');
insert into SYMBOLS values('Npref4n','ENG','Decadal prefix');
insert into SYMBOLS values('Npref5n','ENG','Decadal prefix');
insert into SYMBOLS values('Npref6n','ENG','Decadal prefix');
insert into SYMBOLS values('Npref7n','ENG','Decadal prefix');
insert into SYMBOLS values('Npref8n','ENG','Decadal prefix');
insert into SYMBOLS values('Npref9n','ENG','Decadal prefix');
insert into SYMBOLS values('swVowel','ENG', 'Starts with vowel');
insert into SYMBOLS values('swConsonant','ENG', 'Starts with consonant');
insert into SYMBOLS values('S','ENG', 'Start symbol');

insert into GCAT values('CON', 'Stem', 'ENG', '1',NULL,NULL);
insert into GCAT values('A', 'Stem', 'ENG', '1',NULL,NULL);
insert into GCAT values('A', 'COMP', 'ENG', '1',NULL,NULL);
insert into GCAT values('A', 'SUPER', 'ENG', '1',NULL,NULL);
insert into GCAT values('Adv', 'Stem', 'ENG', '1',NULL,NULL);
insert into GCAT values('Cmpl', 'Stem', 'ENG', '1',NULL,NULL);
insert into GCAT values('Conj', 'Stem', 'ENG', '1',NULL,NULL);
insert into GCAT values('Det', 'Stem', 'ENG', '1',NULL,NULL);
insert into GCAT values('Det', 'Def', 'ENG', '1',NULL,NULL);
insert into GCAT values('Det', 'Indef', 'ENG', '1',NULL,NULL);
insert into GCAT values('Det', 'fwConsonant', 'ENG', '1',NULL,NULL);
insert into GCAT values('Det', 'fwVowel', 'ENG', '1',NULL,NULL);
insert into GCAT values('Inject', 'Stem', 'ENG', '1',NULL,NULL);
insert into GCAT values('N', 'Stem', 'ENG', '1',NULL,NULL);
insert into GCAT values('N', '3pl', 'ENG', '1',NULL,NULL);
insert into GCAT values('N', '3sg', 'ENG', '1',NULL,NULL);
insert into GCAT values('N', 'GEN', 'ENG', '1',NULL,NULL);
insert into GCAT values('NVC', 'Stem', 'ENG', '1',NULL,NULL);
insert into GCAT values('NVC', '1sg', 'ENG', '1',NULL,NULL);
insert into GCAT values('NVC', '2nd', 'ENG', '1',NULL,NULL);
insert into GCAT values('NVC', '3sg', 'ENG', '1',NULL,NULL);
insert into GCAT values('NVC', '1pl', 'ENG', '1',NULL,NULL);
insert into GCAT values('NVC', '3pl', 'ENG', '1',NULL,NULL);
insert into GCAT values('NVC', 'PRES', 'ENG', '1',NULL,NULL);
insert into GCAT values('NVC', 'PAST', 'ENG', '1',NULL,NULL);
insert into GCAT values('NVC', 'wh', 'ENG', '1',NULL,NULL);
insert into GCAT values('NVC', 'neut', 'ENG', '1',NULL,NULL);
insert into GCAT values('NVC', 'masc', 'ENG', '1',NULL,NULL);
insert into GCAT values('NVC', 'fem', 'ENG', '1',NULL,NULL);
insert into GCAT values('Part', 'Stem', 'ENG', '1',NULL,NULL);
insert into GCAT values('Prep', 'Stem', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', 'Stem', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', '1sg', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', '2sg', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', '3sg', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', '1pl', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', '2pl', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', '3pl', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', '2nd', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', '3rd', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', 'nom', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', 'acc', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', 'nomacc', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', 'wh', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', 'fem', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', 'masc', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', 'neut', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', 'reffem', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', 'refmasc', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', 'refl', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', 'NEG', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', 'GEN', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', 'ref1sg', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', 'ref2sg', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', 'ref3sg', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', 'ref1pl', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', 'ref2nd', 'ENG', '1',NULL,NULL);
insert into GCAT values('Pron', 'ref3pl', 'ENG', '1',NULL,NULL);
insert into GCAT values('Punct', 'Stem', 'ENG', '1',NULL,NULL);
insert into GCAT values('Punct', 'Apostrophe', 'ENG', '1',NULL,NULL);
insert into GCAT values('Punct', 'DoubleApostrophe', 'ENG', '1',NULL,NULL);
insert into GCAT values('Punct', 'OpeningBracket', 'ENG', '1',NULL,NULL);
insert into GCAT values('Punct', 'ClosingBracket', 'ENG', '1',NULL,NULL);
insert into GCAT values('Punct', 'Comma', 'ENG', '1',NULL,NULL);
insert into GCAT values('Punct', 'Hyphen', 'ENG', '1',NULL,NULL);
insert into GCAT values('Punct', 'Dash', 'ENG', '1',NULL,NULL);
insert into GCAT values('Punct', 'FullStop', 'ENG', '1',NULL,NULL);
insert into GCAT values('Punct', 'QuestionMark', 'ENG', '1',NULL,NULL);
insert into GCAT values('Punct', 'BackTick', 'ENG', '1',NULL,NULL);
insert into GCAT values('Punct', 'DoubleBackTick', 'ENG', '1',NULL,NULL);
insert into GCAT values('Punct', 'Colon', 'ENG', '1',NULL,NULL);
insert into GCAT values('Punct', 'ExclamationMark', 'ENG', '1',NULL,NULL);
insert into GCAT values('Punct', 'SemiColon', 'ENG', '1',NULL,NULL);
insert into GCAT values('Punct', 'Quotes', 'ENG', '1',NULL,NULL);
insert into GCAT values('Punct', 'OpeningSqBracket', 'ENG', '1',NULL,NULL);
insert into GCAT values('Punct', 'ClosingSqBracket', 'ENG', '1',NULL,NULL);
insert into GCAT values('V', 'Stem', 'ENG', '1',NULL,NULL);
insert into GCAT values('V', '1sg', 'ENG', '1',NULL,NULL);
insert into GCAT values('V', '2sg', 'ENG', '1',NULL,NULL);
insert into GCAT values('V', '3sg', 'ENG', '1',NULL,NULL);
insert into GCAT values('V', '3pl', 'ENG', '1',NULL,NULL);
insert into GCAT values('V', 'CONTR', 'ENG', '1',NULL,NULL);
insert into GCAT values('V', 'NEG', 'ENG', '1',NULL,NULL);
insert into GCAT values('V', 'PRES', 'ENG', '1',NULL,NULL);
insert into GCAT values('V', 'PROG', 'ENG', '1',NULL,NULL);
insert into GCAT values('V', 'PAST', 'ENG', '1',NULL,NULL);
insert into GCAT values('V', 'PPART', 'ENG', '1',NULL,NULL);
insert into GCAT values('V', 'STR', 'ENG', '1',NULL,NULL);
insert into GCAT values('V', 'Aux', 'ENG', '1',NULL,NULL);
insert into GCAT values('V', 'Modal', 'ENG', '1',NULL,NULL);
insert into GCAT values('VVC', 'Stem', 'ENG', '1',NULL,NULL);
insert into GCAT values('VVC', 'PRES', 'ENG', '1',NULL,NULL);
insert into GCAT values('VVC', 'Modal', 'ENG', '1',NULL,NULL);
insert into GCAT values('Num', 'Stem', 'ENG', '1',NULL,NULL);
insert into GCAT values('Num', 'nom', 'ENG', '1',NULL,NULL);
insert into GCAT values('Num', 'ord', 'ENG', '1',NULL,NULL);
insert into GCAT values('Num', 'Npref1n', 'ENG', '1',NULL,NULL);
insert into GCAT values('Num', 'Npref2n', 'ENG', '1',NULL,NULL);
insert into GCAT values('Num', 'Npref3n', 'ENG', '1',NULL,NULL);
insert into GCAT values('Num', 'Npref4n', 'ENG', '1',NULL,NULL);
insert into GCAT values('Num', 'Npref5n', 'ENG', '1',NULL,NULL);
insert into GCAT values('Num', 'Npref6n', 'ENG', '1',NULL,NULL);
insert into GCAT values('Num', 'Npref7n', 'ENG', '1',NULL,NULL);
insert into GCAT values('Num', 'Npref8n', 'ENG', '1',NULL,NULL);
insert into GCAT values('Num', 'Npref9n', 'ENG', '1',NULL,NULL);

COMMIT;