echo "printing parameters and their contents for" $1;
unset out;
unset script;
c=1;
for i in $2;
do 
	echo name;
	echo $i;
	echo content;
	p=$(($c+2));
	eval v="\$$p";
	echo "$v";
	case "$i" in 
		*_out) op="$(echo "$v"|cut -c1)";
			if [ "$op" = "\"" ];
			then dirs="$(echo "$v"|tr "\"\"" "\""|tr "\"" " ")";
				for j in $dirs;
				do 
					script="$script""find $j;";
				done;
				echo "$script";
				eval "$script";
				exit;
			elif [ "$op" = "|" ];
				then OIFS="$IFS";
				IFS="|";
				v="$(echo "$v"|cut -c2-)";
				for j in $v;
				do 
					echo "$j";
					unset path;
					unset options;
					unset optionhead;
					unset pipehead;
					unset pipetail;
					unset script;
					IFS="&";
					for k in $j;
					do 
						echo "$k";
						case "$k" in 
							*-path*) if [ "$(echo "$k"|cut -c1)" != "!" ];
								then path="$path ""$(echo "$k"|sed "s/-path//g")";
								else options="$options ""$(echo "$k"|sed "s/ \"/ \"*\//g")";
									options="${options%?}""/*\"";
								fi;
							 ;;
							*-L*) if [ "$(echo "$k"|cut -c1)" != "!" ];
								then optionhead="-L";
									pipehead="grep \"\$(find ";
									pipetail=" -type l)\"";
								else pipehead="grep -v \"\$(find -H ";
									pipetail=" -type l -ls|cut -f2 -d\">\"|cut -c2-)\"";
								fi;
							 ;;
							*) options="$options ""$k";							
							 ;;
						esac;
					done;
					if [ -z "$path" ];
					then path="./";
					fi;
					if [ -z "$pipehead" ];
						then script="find ""$path ""-type d $options";
						else script="find ""$optionhead ""$path ""-type d $options""|$pipehead ""$path ""$pipetail";
					fi;
					echo "$script";
					eval "$script";
					IFS="|";
				done;
				exit;
			elif [ -z "$op" ];
				then script="find ./ -type d";
				echo "$script";
				eval "$script";
			fi;
		 ;;
	esac;
	c=$(($c+1));
done;
eval "$1"_out=$1;